name: flutter_advanced_networkimage_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  path_provider: "^0.3.0"  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true