name: flutter_advanced_networkimage_example
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  flutter_advanced_networkimage:
    path: ../

flutter:
  uses-material-design: true
