name: flutter_advanced_networkimage
description: An advanced image provider for flutter.
version: 0.0.3
author: fuyumi
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: any
  path_provider: "^0.3.0"
  quiver: '>=0.26.2 <0.27.0'

dev_dependencies:
  test: ^0.12.0

environment:
    sdk: ">=1.8.0 <2.0.0"