name: flutter_advanced_networkimage
description: An advanced image provider for flutter.
version: 0.1.1
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3+14"
  path_provider: "^0.3.0"
  quiver: ">=0.26.2 <0.27.0"
  path: "^1.4.2"
  crypto: "^2.0.2+1"

environment:
    sdk: ">=1.8.0 <2.0.0"