name: flutter_advanced_networkimage
description: An advanced image provider for flutter.
version: 0.1.7
author: "fuyumi <fnatic.roach@gmail.com>"
homepage: https://github.com/mchome/flutter_advanced_networkimage

dependencies:
  flutter:
    sdk: flutter
  http: "^0.11.3"
  path_provider: "^0.3.1"
  quiver: ">=0.28.0 <0.29.0"
  path: "^1.5.1"
  crypto: "^2.0.2"

environment:
    sdk: ">=1.8.0 <2.0.0"